/** Desktop IPC channels per page — used for parity checks and feature panels */
export const PAGE_CHANNELS = {
  dashboard: [
    'get-dashboard-stats', 'get-live-feed', 'get-trending-topics', 'get-live-news', 'get-setup-status',
    'get-campaign-mastery-status', 'mark-campaign-mastery-step',
    'get-active-campaign', 'get-domain-metrics', 'get-domdetailer-metrics', 'get-project-metrics', 'analyze-topic',
    'discover-best-questions', 'get-unanswered-questions', 'get-qa-settings', 'get-qa-sources', 'get-qa-ad-suggestions',
    'search-discovered-posts', 'compose-qa-answer', 'publish-qa-answer', 'get-leads', 'scan-reddit-now',
    'get-watched-monitors', 'get-auto-search-settings', 'get-worker-status', 'get-worker-tasks', 'start-worker',
    'stop-worker', 'trigger-full-auto-search', 'get-fanpage-settings', 'get-fanpage-metrics', 'save-fanpage-settings',
    'run-fan-acquisition-now', 'run-fanpage-hands-free-now', 'get-engagement-queue', 'retry-engagement-queue',
    'engage-post', 'draft-post-reply', 'save-ai-reply', 'export-data', 'curate-from-rss', 'search-stock-photo',
    'serp-search', 'generate-image', 'schedule-post', 'publish-post', 'get-section-live',
  ],
  videoStudio: [
    'get-imperial-video-studio-config', 'get-imperial-video-tool-registry', 'get-imperial-video-skills-index',
    'run-imperial-video-pipeline', 'get-imperial-video-pipeline-result', 'clear-imperial-video-pipeline-result', 'analyze-reference-video',
    'run-imperial-video-compose', 'grok-generate-video', 'grok-imagine', 'grok-ask-text', 'grok-get-status',
    'export-design-subtitles', 'compose-social-layout', 'generate-viral-thumbnail', 'search-stock-photo',
    'play-tts', 'publish-post', 'schedule-post', 'get-content-library', 'get-section-live',
  ],
  contentHub: [
    'get-imperial-pipeline-config', 'run-imperial-pipeline', 'get-imperial-pipeline-result',
    'get-imperial-video-studio-config', 'run-imperial-video-pipeline',
    'publish-post', 'schedule-post', 'generate-ai', 'generate-image', 'search-stock-photo',
    'curate-from-rss', 'run-content-studio', 'generate-content-batch', 'get-content-studio-config',
    'generate-viral-thumbnail', 'generate-viral-thumbnail-batch', 'get-thumbnail-studio-config',
    'grok-ask-text', 'grok-imagine', 'grok-generate-video', 'grok-generate-infographic', 'grok-get-status',
    'compose-qa-answer', 'publish-qa-answer', 'get-content-queue', 'remove-content-queue-item',
    'get-auto-content-settings', 'save-auto-content-settings', 'run-content-scheduler-now',
    'discover-site-rss', 'get-site-rss-sources', 'save-site-rss-source', 'run-category-rss-router',
    'get-ai-replies', 'publish-ai-reply', 'update-ai-reply', 'delete-ai-reply',
    'serp-search', 'shorten-url', 'deepl-translate', 'play-tts', 'contentful-fetch',
    'get-streaming-keys', 'get-youtube-channels', 'generate-carousel-fal', 'research-keyword',
    'run-auto-rules-now', 'get-post-history', 'get-dashboard-stats',
    'get-content-studio-live', 'get-content-library', 'get-brand-guidelines',
    'seed-brand-from-website', 'get-design-templates', 'render-design-post',
    'get-dns-sites', 'get-dns-records', 'save-dns-record', 'apply-dns-records', 'sync-dns-sites',
    'generate-from-library-assets', 'schedule-content-batch', 'get-section-live',
    'get-format-templates', 'recreate-from-format-template',
    'get-active-campaign', 'get-keywords', 'grok-build-prompt-preview',
  ],
  browsePosts: [
    'get-live-feed', 'get-keywords', 'get-linked-accounts', 'get-dashboard-stats',
    'get-all-post-history', 'get-fetch-profiles', 'save-fetch-profile', 'delete-fetch-profile',
    'draft-post-reply', 'save-ai-reply', 'engage-post', 'get-engagement-queue', 'retry-engagement-queue',
    'get-watched-monitors', 'save-watched-monitors', 'schedule-post', 'publish-post',
    'get-live-news', 'search-stock-photo', 'generate-image', 'get-browse-posts-live',
    'get-trending-topics', 'generate-ai',
  ],
  contentLibrary: [
    'get-content-library', 'save-content-asset', 'delete-content-asset', 'import-website-to-library',
    'import-rss-to-library', 'import-text-to-library', 'upload-local-media', 'get-section-live',
    'get-brand-guidelines', 'grok-get-status', 'grok-imagine', 'grok-ask-text',
    'analyze-library-image', 'save-format-template-from-asset', 'get-format-templates',
  ],
  designStudio: [
    'get-design-templates', 'save-design-template', 'delete-design-template', 'render-design-post',
    'generate-from-library-assets', 'get-content-library', 'get-section-live',
    'get-brand-guidelines', 'grok-get-status', 'grok-imagine', 'grok-ask-text',
    'get-format-templates', 'recreate-from-format-template', 'analyze-library-image',
    'save-format-template-from-asset', 'generate-image',
    'get-design-compositor-config', 'compose-social-layout', 'scan-design-pii',
    'apply-design-filters', 'generate-atelier-layout', 'export-design-subtitles',
    'get-design-projects', 'save-design-project',
  ],
  brand: [
    'get-brand-guidelines', 'save-brand-guidelines', 'seed-brand-from-website', 'get-active-campaign',
    'get-section-live', 'grok-get-status', 'grok-ask-text', 'grok-imagine',
  ],
  calendar: [
    'get-scheduled-posts', 'get-calendar-status', 'get-best-post-times', 'schedule-post',
    'publish-scheduled-post-now', 'delete-scheduled-post', 'process-due-scheduled-posts',
    'get-upcoming-by-platform', 'get-calendar-settings', 'get-background-run-settings',
    'get-linked-accounts', 'get-section-live',
  ],
  keywords: [
    'get-keywords', 'save-keywords', 'delete-keyword', 'generate-keywords', 'research-keyword',
    'generate-global-custom-prompt', 'get-keyword-api-status', 'get-active-campaign', 'get-settings',
    'save-settings', 'get-section-live',
  ],
  seoTools: [
    'get-seo-tools-list', 'run-seo-tool', 'get-section-live', 'get-keyword-api-status',
  ],
  scheduler: [
    'get-scheduled-posts', 'get-background-run-settings', 'save-background-run-settings',
    'get-background-run-status', 'add-background-run-slot', 'delete-background-run-slot',
    'process-due-scheduled-posts', 'get-calendar-status', 'get-section-live',
  ],
  promptVault: [
    'get-prompt-vault', 'search-prompt-vault', 'save-prompt-vault-item', 'delete-prompt-vault-item', 'dedupe-prompt-vault',
    'create-prompt-vault-from-keyword', 'load-prompt-vault-item', 'export-prompt-vault', 'get-section-live',
  ],
  redditAi: [
    'get-reddit-ai-status', 'get-reddit-ai-queue', 'get-reddit-ai-settings', 'save-reddit-ai-settings',
    'run-reddit-ai-module', 'approve-reddit-ai-action', 'dismiss-reddit-ai-action', 'clear-reddit-ai-queue', 'get-leads', 'get-section-live',
  ],
  onboarding: [
    'get-setup-status', 'check-api-status', 'get-settings', 'save-settings', 'set-active-campaign',
    'get-active-campaign', 'save-brand-guidelines', 'get-global-keys', 'save-global-keys', 'get-key-sources',
    'test-all-connections', 'run-live-connection-audit', 'generate-keywords', 'save-keywords', 'get-keywords',
    'get-keyword-api-status', 'get-live-feed', 'trigger-full-auto-search', 'generate-global-custom-prompt',
    'get-watched-monitors', 'save-watched-monitors', 'get-auto-rules', 'save-auto-rules',
    'save-auto-search-settings', 'start-worker', 'set-onboarding-complete', 'set-onboarding-feed-previewed',
    'seed-brand-from-website', 'get-section-live', 'get-linked-accounts',
  ],
  accountHub: [
    'get-linked-accounts', 'get-account-hub-status', 'refresh-account-profile', 'connect-platform',
    'begin-platform-oauth', 'finish-platform-oauth-connect', 'use-selected-accounts', 'unlink-account',
    'get-account-automation-targets', 'save-automation-target-selection', 'set-account-proxy',
    'get-proxy-pool', 'dedupe-linked-accounts', 'get-section-live',
  ],
  accountCreator: [
    'get-proxy-pool', 'save-proxy', 'delete-proxy', 'test-proxy', 'get-profile-kits',
    'generate-profile-kit', 'generate-bulk-profile-kits', 'delete-profile-kit', 'export-profile-kit',
    'push-kit-schedule-to-calendar', 'apply-kit-browser-automation', 'upload-kit-to-linked-accounts',
    'schedule-browser-batch', 'get-browser-batch-status', 'run-browser-batch-now', 'cancel-browser-batch',
    'dedupe-profile-kits', 'clear-qa-profile-kits', 'get-account-creator-status', 'get-section-live',
  ],
  dashboardUsers: [
    'get-billing-plan', 'get-section-live',
  ],
  dashboardAdmin: [
    'get-section-live',
  ],
  dashboardIssues: [
    'get-active-issues', 'get-issues-ledger', 'run-guardian-scan',
    'approve-issue-patch', 'deny-issue-patch', 'edit-issue-patch',
    'delete-issue', 'dispatch-issue-diagnostic-email', 'get-section-live',
  ],
  campaignManager: [
    'get-settings-status', 'get-active-campaign', 'get-settings', 'get-campaign-details',
    'update-campaign', 'pause-campaign', 'resume-campaign', 'delete-campaign', 'set-active-campaign',
    'clear-qa-campaigns', 'clear-failed-scheduled-posts',
    'save-settings', 'get-scheduled-posts', 'schedule-post', 'update-scheduled-post',
    'delete-scheduled-post', 'publish-scheduled-post-now', 'get-worker-status', 'get-section-live',
    'get-verified-node-tree', 'list-verified-campaigns', 'create-verified-campaign',
    'discover-verify-platform-tree', 'run-node-verification', 'run-verification-loop-all',
    'bind-campaign-verified-nodes', 'set-campaign-control', 'get-platform-discovery-schema',
  ],
} as const;